//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkNotepad {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class SettingsStylize : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsStylize defaultInstance = ((SettingsStylize)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsStylize())));
        
        public static SettingsStylize Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color Background {
            get {
                return ((global::System.Drawing.Color)(this["Background"]));
            }
            set {
                this["Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color Background_Highlight {
            get {
                return ((global::System.Drawing.Color)(this["Background_Highlight"]));
            }
            set {
                this["Background_Highlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color Text {
            get {
                return ((global::System.Drawing.Color)(this["Text"]));
            }
            set {
                this["Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130, 100, 255")]
        public global::System.Drawing.Color Link {
            get {
                return ((global::System.Drawing.Color)(this["Link"]));
            }
            set {
                this["Link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70, 50, 205")]
        public global::System.Drawing.Color Link_Pressed {
            get {
                return ((global::System.Drawing.Color)(this["Link_Pressed"]));
            }
            set {
                this["Link_Pressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color Button {
            get {
                return ((global::System.Drawing.Color)(this["Button"]));
            }
            set {
                this["Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 60")]
        public global::System.Drawing.Color Button_Highlight {
            get {
                return ((global::System.Drawing.Color)(this["Button_Highlight"]));
            }
            set {
                this["Button_Highlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60, 90")]
        public global::System.Drawing.Color Button_Pressed {
            get {
                return ((global::System.Drawing.Color)(this["Button_Pressed"]));
            }
            set {
                this["Button_Pressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color Button_Text {
            get {
                return ((global::System.Drawing.Color)(this["Button_Text"]));
            }
            set {
                this["Button_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color Button_Unavailable {
            get {
                return ((global::System.Drawing.Color)(this["Button_Unavailable"]));
            }
            set {
                this["Button_Unavailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color Button_Unavailable_Text {
            get {
                return ((global::System.Drawing.Color)(this["Button_Unavailable_Text"]));
            }
            set {
                this["Button_Unavailable_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50, 50")]
        public global::System.Drawing.Color Button_Unavailable_Highlight {
            get {
                return ((global::System.Drawing.Color)(this["Button_Unavailable_Highlight"]));
            }
            set {
                this["Button_Unavailable_Highlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 75")]
        public global::System.Drawing.Color Button_Unavailable_Pressed {
            get {
                return ((global::System.Drawing.Color)(this["Button_Unavailable_Pressed"]));
            }
            set {
                this["Button_Unavailable_Pressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color Button_Border {
            get {
                return ((global::System.Drawing.Color)(this["Button_Border"]));
            }
            set {
                this["Button_Border"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color TextBox {
            get {
                return ((global::System.Drawing.Color)(this["TextBox"]));
            }
            set {
                this["TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 240, 240")]
        public global::System.Drawing.Color TextBox_Text {
            get {
                return ((global::System.Drawing.Color)(this["TextBox_Text"]));
            }
            set {
                this["TextBox_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Text_Error {
            get {
                return ((global::System.Drawing.Color)(this["Text_Error"]));
            }
            set {
                this["Text_Error"] = value;
            }
        }
    }
}
